### ISSUE TITLE
Unable to block an ip for ssh brute force attack

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-ruleset#106]
I have tried this link 

https://blog.wazuh.com/blocking-attacks-active-response/

But when i tried to use rule, it didnt ban any ip that used for ssh bruteforce attack...
What could go wrong with my configuration ?

below is my configuration in `ossec.conf`

```
<command>
    <name>firewall-drop</name>
    <executable>firewall-drop.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>yes</timeout_allowed>
</command>
```

**Active-response**
```
<active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>5712</rules_id> 
    <timeout>1800</timeout> 
</active-response>
```

**Comment by gagantous** [comment]
DO i have to install `iptables`  first ?

**Comment by frgv** [comment]
Hi!

Since `firewall-drop.sh` adds an IP entry to the system firewall, yes, you must install `iptables` (if you are running Wazuh on Linux), `ipfilter` (if you are on Solaris, Freebsd or Netbsd) or `IPSec` (if you are on AIX).

On the other hand, if you have `firewalld` installed, you always can use `firewalld-drop.sh` instead of `firewall-drop.sh`.

I hope this answers your question. 

Best regards,

Fran González.

**Comment by gagantous** [comment]
Hi @frgv !
Thanks for the reply. i have a question.
how about if i used `host.deny` ?
how do i do that ?

**Comment by gagantous** [comment]
Hi @frgv!
I have tried `firewall-d` and it works!!! 
Thank you @frgv for your support.

And one last question, i have installed `iptables` too on a different machine. but it didnt ban an ip, even if i have set the command just like `host-deny` and `firewalld-drop`.

Do you know what is the problem for my `iptables` ?

Regards
Fathin
