### ISSUE TITLE
Wrong rule level

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-ruleset#142]
Hello team, the next rule should has a lower level:

```xml
<rule id="216" level="15">
    <if_sid>210</if_sid>
    <status>lost</status>
    <description>Remote upgrade failed. Agent disconnected.</description>
    <group>upgrade,upgrade_failure,</group>
</rule>
```

If the team thinks the rule level is fine, I want to know why, thanks in advance.

Regards,
Jesús

**Comment by frgv** [comment]
It makes sense to me. Let's see why:

Imagine you have an environment with 200 active agents. Then you start to upgrade all the agents using the remote upgrade capabilities. It works for 197, but, somehow, the upgrade has failed with 3 agents, and they will be disconnected. 

If I were you, I would like to have knowledge of this situation ASAP, because can lead to miss lots of data, PCI noncompliance, etc. This is a real problem to tackle urgently.

So, for me, it makes lots of sense. Let's see what are the thoughts of the rest of the team.

Best regards,

Fran G.

**Comment by SitoRBJ** [comment]
Hello team, 

Thank you for your contributions **jesusgn90** and **frgv**. In this case, we will maintain the level of the rule. The example that **frgv** has given is a good one. It is important for users to be aware of the "loss" of agents in upgrades. For example, we may think that losing the data of such agents is similar to suffering an attack that has the same repercussion. 

We proceed to close the issue.

Kind regards,

Alfonso Ruiz-Bravo
