### ISSUE TITLE
Is it possible for ossec to detect DDoS ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-ruleset#152]
I have been trying to DoS one of my wazuh agent, and it's not produce any log, nor in syslog, or access.log.
Is it possible for wazuh ossec to detect DDoS attack ?

**Comment by SitoRBJ** [comment]
Hello gagantous,

There is nothing configured for this in Wazuh. This does not mean that we cannot configure certain options to interpret this type of attack and act if possible, however, due to performance, we recommend the use of third-party tools designed for this purpose.

For example, an Apache web server obtains logs of each request. We could create a rule that detects if an event recorded by the Apache web server (a request) happens repeatedly, and then triggers the active response and blocks the network. 

This way of action would be viable, but there are tools to detect DDoS attacks in a faster and more precise way, such as ModSecurity.  

Kind regards,

Alfonso Ruiz-Bravo

**Comment by SitoRBJ** [comment]
Hello @gagantous,

It's been more than a month since the last response to this issue, so we will proceed to close it. 

If you have more questions or problems, feel free to open a new issue.

Kind regards,

Alfonso Ruiz-Bravo

**Comment by akshanshshrivastava** [comment]
any update on this

**Comment by gagantous** [comment]
@akshanshshrivastava They said we need to use another third party apps
