### ISSUE TITLE
Sysmon Event 11 decoder mistake

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh-ruleset#181]
Hi, I noticed that the decoder for sysmon event 11 is `File created: (\.*)\s+UtcTime:` while the event itself is `File created: RuleName: UtcTime:` the outcome of this is  `"filecreated":"RuleName:"`. I changed it to `File created: (\.*)\s+RuleName: \.*\s+UtcTime:` so it will ignore RuleName.

Also, and more importantly, it seems that the decoder cannot handle spaces in the Image and TargetFileName fields which results in the data not being decoded at all. any idea why?

Thanks in advance!

**Comment by elwali10** [comment]
Hello @agentsofshield 

Sorry for the late reply,

Would it happen to have full logs for these cases ? is it still the case with our new version of ruleset not being decoded, if so sharing logs would be helpful to reply to your request.

I would take the chance to invite your join our Mailing list community https://groups.google.com/forum/#!forum/wazuh , in order to get prompt response.

I will close this issue, i would really appreciate it if you open a thread for it in our mailing list if further help is requested.

Hope to help.
Regards,
