### ISSUE TITLE
Squid decoder is very general

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-ruleset#224]
Squid decoder is very general and is easy that it overlaps custom decoders.

Here an example: https://groups.google.com/forum/#!topic/wazuh/qukCJjuFF7A

Squid decoder overlaps his custom decoder.

**Comment by joselopezrio** [comment]
Hello team,

we have plans to change the `squid-acesslog` decoder at `/var/ossec/ruleset/decoders/0275-squid-decoders.xml` in order to fix this issue. 

As these changes **could affect user custom decoders and rules** they will be included in the next major version, with previous notifications during the following minor releases. 


Regards,
Jose Manuel Lopez

**Comment by joselopezrio** [comment]
Merged here #672
