### ISSUE TITLE
Configured windows events not being sent to wazuh manager

### ISSUE THREAD

**Issue by adalbertor01** [wazuh/wazuh-ruleset#266]
<localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907]</query>
  </localfile>

This is part of the agent ossec.conf file, these events (when triggered) are shown on security event viewer but not in ELK discover tab or wazuh agent discover tab. Am I missing something in the configuration?
Thanks in advanced for your help.

I have installed the wazuh appliance 3.7.0, CentOS 7
Adalberto

**Comment by elwali10** [comment]
Hello @adalbertor01 

Sorry for the late reply. 
If you are using this configuration (which is the default one i believe) , you are filtering all the logs (Events) with the IDs (5154 , 5474 ...) in a Wazuh Level. Hence it is expected to be able seeing them in the Security Event Viewer and Not in ELK ( Wazuh).

If you wish integrating this logs (events), remove the query part in your agent configuration, then restart the wazuh agent :

```
 <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
  </localfile>

```

Here : https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=localfile#query, you can find out more about options to use in localfile.

I will take the chance to invite to our mailing list, in order to get a prompt answer : https://groups.google.com/forum/#!forum/wazuh

I'm closing the issue for the moment, don't hesitate re-opening it if any further help is requested.

Hope this helps,
Regards,
