### ISSUE TITLE
Is there any pdf format that explain all the ruleset for each ID rules ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-ruleset#268]
Does wazuh provide the pdf format that explain all the rules from rules ID 1 to rules ID x ? I mean like what does each rules did and such like that.

Thanks in advanced!

**Comment by elwali10** [comment]
Hello @gagantous,

I'm afraid that's not the case for the moment.

what would the use case where you would need the whole descriptions for the ruleset ?

I will take the chance to let you know about our mailing list : https://groups.google.com/forum/#!forum/wazuh, In order to have more prompt answers.

Regards,
Wali.k
