### ISSUE TITLE
Wazuh Version 2 Rule Update Error

### ISSUE THREAD

**Issue by stephenh1991** [wazuh/wazuh-ruleset#33]
Hi!

Not sure if you are aware but I think the "update_ruleset.py" is pulling down the incorrect files from github.

When run I get the error:
ERROR: Unkown: [Errno 2] No such file or directory: '/var/ossec/tmp/ruleset/downloads/wazuh-ruleset/update_ruleset.py'.

When looking at the directory:

-rw-r-----. 1 root ossec 3.4K Mar 14 10:37 CHANGELOG.md
-rw-r-----. 1 root ossec  47K Mar 14 10:37 ossec_ruleset.py
-rw-r-----. 1 root ossec 2.2K Mar 14 10:37 README.md
drw-r-----. 2 root ossec 4.0K Mar 14 10:37 rootcheck
drw-r-----. 9 root ossec 4.0K Mar 14 10:37 rules-decoders
-rw-r-----. 1 root ossec  83K Mar 14 10:37 Ruleset_Reference.ods
drw-r-----. 5 root ossec   74 Mar 14 10:37 tools
-rw-r-----. 1 root ossec    5 Mar 14 10:37 VERSION

Seems like it's pulling down the old: ossec_ruleset.py script instead of update_ruleset.py.

Thanks,
Steve

**Comment by snaow** [comment]
Hi @stephenh1991 

That error is due to we have not released the new version of ruleset. The script is trying to download the old ruleset version, and in that version it doesn't exist the directory "wazuh-ruleset".

Right now, you can use the script from the Wazuh ruleset repository, using argument "--source", specifying a local directory for loading the rules.

```
git clone https://github.com/wazuh/wazuh-ruleset.git
cd wazuh-ruleset
./update_ruleset.py --source .
```

Thanks for your feedback! We really appreciate it.

**Comment by stephenh1991** [comment]
Hi @snaow 

Thanks for the quick reply, that worked perfectly!

We've setup a cron job to grab this weekly until the full release.
