### ISSUE TITLE
Guide for own rules and decoders missing - OSSEC vs WAZUH feature set

### ISSUE THREAD

**Issue by VAdamec** [wazuh/wazuh-ruleset#34]
Maybe I'm missed something, but how can I create own decoder with features which Wazuh brings ? I cannot follow same steps as for OSSEC as it seems that new rules is applied in different way. For example I would like to create simple decoder for Hashicorp Vault audit log. I look to Wazuh rulest (for example 0040-auditd_decoders.xml) and based on that I made this very raw decoder:

/var/ossec/etc/local_decoder.xml

```
<decoder name="vault">
    <prematch>^\.*{"time":"\.*","type":"\.*$</prematch>
</decoder>

<decoder name="vault-response">
  <parent>vault</parent>
  <regex>^{"time":"(\.*)","type":"(\.*)","error":"(\.*)","auth":{"client_token":"(\.*)","accessor":"(\.*)","display_name":"(\.*)","policies":null,"metadata":null},"request":{"id":"(\.*)","operation":"(\.*)","client_token":"(\.*)","path":"(\.*)","data":null,"remote_address":"(\.*)","wrap_ttl":0},"response":{"data":{"(\.*)"}}}$</regex>
 <order>time,type,errmsg,client_token,accessor,display_name,req_id,operation,request_token,path,remote_ip,response</order>
</decoder>
```

but when I restart OSSEC I get error:

```
code-xml: Wrong field 'time' in the order of decoder 'vault-response'
```
 
which make sense for original OSSEC as it support only specific order items.

http://ossec-docs.readthedocs.io/en/latest/syntax/head_decoders.html#element-decoder.order

**Comment by alberpilot** [comment]
Hello VAdamec

  Thanks for your feedback. I have tried your decoder in one of my manager and I haven't these error, for me is working fine. Could you please tell us what version of Wazuh have you installed?

`cat /etc/ossec-init.conf`

If you are not using Wazuh 2.0 is possible that the field time was not being treated as a dynamic field. 

Best regards,

**Comment by VAdamec** [comment]
DIRECTORY="/var/ossec"
VERSION="v2.9.0"
WAZUH_VERSION="v1.1.1"
DATE="Thu Apr  6 05:54:02 PDT 2017"
TYPE="server"

**Comment by alberpilot** [comment]
Hello VAdamec

  As we expected, you're using an not updated version of Wazuh, that's why doesn't recognize the field time as dynamic field.

Please, consider perform a new instalation following the documentation:

https://documentation-dev.wazuh.com/index.html

In case of stay in 1.1.1 will be necessary to use the "static" fields:

- location - where the log came from (only on FTS)
- srcuser - extracts the source username
- dstuser - extracts the destination (target) username
- user - an alias to dstuser (only one of the two can be used)
- srcip - source ip
- dstip - dst ip
- srcport - source port
- dstport - destination port
- protocol - protocol
- id - event id
- url - url of the event
- action - event action (deny, drop, accept, etc)
- status - event status (success, failure, etc)
- extra_data - Any extra data

You will find severals new features and fixes in the new Wazuh version, we highly recommend it. Of course, don't hesitate to write again for any kind of questions. 

Best regards,

**Comment by VAdamec** [comment]
ok, thanks
