### ISSUE TITLE
Error updating rulesets with wazuh-manager package.

### ISSUE THREAD

**Issue by sc-chad** [wazuh/wazuh-ruleset#35]
Using the wazuh-manager package I tried updating the rules via:
`/var/ossec/bin/update_ruleset.py`

Fails with error:
```
### Wazuh ruleset ###
ERROR: Unkown: [Errno 2] No such file or directory: '/var/ossec/tmp/ruleset/downloads/wazuh-ruleset/update_ruleset.py'.
Exiting.
```

Tried updating via the automatic method script and it fails with:
```
sudo /var/ossec/update/ruleset/ossec_ruleset.py -a

OSSEC Wazuh Ruleset [0.100], 20170412

Creating a backup for folders '/var/ossec/etc' and '/var/ossec/rules'.
	Backup folder: /var/ossec/update/ruleset/backups/20170412_002
	[Done]

Checking directory structure.
	Error: It seems that we could not identify your installation. Install the ruleset manually or contact us for assistance.```


Which method are we supposed to use for weekly rules updates?

Thanks for all the effort btw! Great product!

**Comment by jesuslinares** [comment]
Hi,

`ossec_ruleset.py` is deprecated in Wazuh 2.0. You must use `/var/ossec/bin/update_ruleset.py`. 

By default, the script downloads the ruleset for the stable branch. This branch is not updated yet to the new directory layout because we didn't release Wazuh 2.0. So, **for now it is not possible to use the script from /var/ossec/bin.** If you want to use it, you can clone this repository and call the script using the argument:

`--source .`

In this way, the script will take the files from the current directory instead of trying to download it from the stable branch.

I know it's a bit confusing, but we are close to release the new version!.

Thanks.
Regards.

**Comment by sc-chad** [comment]
Perfect that worked.  Thanks @jesuslinares!

Loving the new version, had some initial issues with getting ossec-authd working correctly to remotely sign certificates but everything else worked perfectly!

Great job!
