### ISSUE TITLE
Building custom rules for windows security events

### ISSUE THREAD

**Issue by CYM5** [wazuh/wazuh-ruleset#448]
Hi there, 

I would like to create a rule to raise an alert when a new user is added to a domain. This event appears in security log, with id 5136. 
I'm stuck cause I can't use ossec-logtest with the windows log format (XML), it's seams wazuh uses a json format, is there a way to quickly transform my XML windows log into json wazuh friendly format ? 

I have already checked in my manager's log, there is no raw json log that I seek. 

Thanks a lot for any help.

cym5

**Comment by Lopuiz** [comment]
Hi @CYM5 


To capture the event 5136 I recommend you to activate the option [logall](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall) in the manager `ossec.conf`. With this option active, `/var/ossec/log/archive/archive.log` will be created. This file contains all log messages that are processed by Analysisd.

Connects the agent to the manager and generates event 5136. This event must be sent to the agent and written in `archive.log`.

There are two formats [to collect Windows logs](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html?highlight=eventlog): 

+ **Eventlog** (supported by every Windows version)
The following is an example of an event sent in **Eventlog** format.

>2019 Jun 24 11:14:55 (WIN-S0GE7HFOP5K) 10.0.0.8->WinEvtLog 2019 Jun 24 05:14:53 WinEvtLog: Microsoft-Windows-Sysmon/Operational: INFORMATION(22): Microsoft-Windows-Sysmon: SYSTEM: NT AUTHORITY: WIN-S0GE7HFOP5K: Dns query:  RuleName:   UtcTime: 2019-06-24 15:14:52.542  ProcessGuid: {E6A6834E-90A7-5D10-0000-0010C98D5100}  ProcessId: 1152  QueryName: pipeline-edge-prod-25-561439127.us-west-2.elb.amazonaws.com  QueryStatus: 9501  QueryResults:   Image: C:\Program Files (x86)\Mozilla Firefox\firefox.exe

Note that the event starts at the second timestamp. The header is added by manager: `2019 Jun 24 11:14:55 (WIN-S0GE7HFOP5K) 10.0.0.8->WinEvtLog 2019`. The rest of the message can already be entered in `ossec-logtest`.

And the `ossec-logtest` output is:
```
lopezziur-S551LN ossec # bin/ossec-logtest 
2019/07/09 20:28:02 ossec-testrule: INFO: Started (pid: 9078).
ossec-testrule: Type one log per line.

Jun 24 05:14:53 WinEvtLog: Microsoft-Windows-Sysmon/Operational: INFORMATION(22): Microsoft-Windows-Sysmon: SYSTEM: NT AUTHORITY: WIN-S0GE7HFOP5K: Dns query: RuleName: UtcTime: 2019-06-24 15:14:52.542 ProcessGuid: {E6A6834E-90A7-5D10-0000-0010C98D5100} ProcessId: 1152 QueryName: pipeline-edge-prod-25-561439127.us-west-2.elb.amazonaws.com QueryStatus: 9501 QueryResults: Image: C:\Program Files (x86)\Mozilla Firefox\firefox.exe


**Phase 1: Completed pre-decoding.
       full event: 'Jun 24 05:14:53 WinEvtLog: Microsoft-Windows-Sysmon/Operational: INFORMATION(22): Microsoft-Windows-Sysmon: SYSTEM: NT AUTHORITY: WIN-S0GE7HFOP5K: Dns query: RuleName: UtcTime: 2019-06-24 15:14:52.542 ProcessGuid: {E6A6834E-90A7-5D10-0000-0010C98D5100} ProcessId: 1152 QueryName: pipeline-edge-prod-25-561439127.us-west-2.elb.amazonaws.com QueryStatus: 9501 QueryResults: Image: C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
       timestamp: 'Jun 24 05:14:53'
       hostname: 'lopezziur-S551LN'
       program_name: 'WinEvtLog'
       log: 'Microsoft-Windows-Sysmon/Operational: INFORMATION(22): Microsoft-Windows-Sysmon: SYSTEM: NT AUTHORITY: WIN-S0GE7HFOP5K: Dns query: RuleName: UtcTime: 2019-06-24 15:14:52.542 ProcessGuid: {E6A6834E-90A7-5D10-0000-0010C98D5100} ProcessId: 1152 QueryName: pipeline-edge-prod-25-561439127.us-west-2.elb.amazonaws.com QueryStatus: 9501 QueryResults: Image: C:\Program Files (x86)\Mozilla Firefox\firefox.exe'

**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Microsoft-Windows-Sysmon/Operational'
       status: 'INFORMATION'
       id: '22'
       extra_data: 'Microsoft-Windows-Sysmon'
       dstuser: 'SYSTEM'                                                                                                  
       system_name: 'WIN-S0GE7HFOP5K'                                                                                      
                                                                                                                            
**Phase 3: Completed filtering (rules).                                                                                      
       Rule id: '18101'                                                                                                         
       Level: '0'                                                                                                                 
       Description: 'Windows informational event.' 
```

+ **Eventchannel** (for Windows prior or equal to Vista)
If you want to capture events in Eventchannel format the received event will be in JSON format, and can also be found in `archive.log`.

The JSON decoder is implemented in C, not XML. Logtest only allows to test rules and decoders in XML, so to test Eventchannel rules a 60000 rule must be modified. All the others depend on this rule. In order to coincide with this, the value of the label `<decode_as>` must be modified to `<decode_as>json</decode_as>`.

Please note that this change is only to test the rules, then it must return to your original state.

The rule I refer to is:
https://github.com/wazuh/wazuh-ruleset/blob/7b7c9e2828b298dac07265723bd42a82974bd180/rules/0575-win-base_rules.xml#L15


I hope this helps you. If you have further questions let us know.

Best regards, Eva

**Comment by CYM5** [comment]
Thank you Eva for your quick reply. It was really clear and helpful. 

Can I let this issue open until all my tests are over ? Please

Best regards

**Comment by Lopuiz** [comment]
You're welcome. Community comes first.
And yes, you can let this issue open. If you have futher questions let us know.

Best regards, Eva

**Comment by CYM5** [comment]
Hi, all is good for me. 

Thank again for your help. 

I close the issue.

Bye
