### ISSUE TITLE
SCA - Ubuntu Boot Loader Password

### ISSUE THREAD

**Issue by rhysxevans** [wazuh/wazuh-ruleset#463]
Hi

The rule id: 5012  seems to be incorrect and not aligned to the CIS document

Rule 5012 is looking in /boot/grub/menu.lst `'f:/boot/grub/menu.lst -> NIN !r:^# && r:password;'`

While the  "CIS Ubuntu Linux 18.04 LTS Benchmark - v1.0.0 - 08-13-2018"
Section 1.4.2 page 67  states

`grep "^set superusers" /boot/grub/grub.cfg `
`grep "^password" /boot/grub/grub.cfg`

So basically we should be looking at the /boot/grub/grub.cfg file ?

Thanks

**Comment by cristgl** [comment]
Hello @rhysxevans,

You are correct, we have already fixed it for the next version in [this file](https://github.com/wazuh/wazuh-ruleset/blob/8e7c685c8a5e3182ee9efabdf4d00e1ab6c23eb2/sca/debian/cis_debian9_L1.yml#L258).

Also notice that we have split the Debian policies into two levels for Debian 7, 8 and 9. The generic Debian policy, _cis_debian_linux_rcl.yml_, has been renamed to _sca_unix_audit.yml_ which now contains some more checks from other files.

Thank you for contributing to the project and giving your feedback.

Kind regards,
Cristina

**Comment by rhysxevans** [comment]
Hi

Thanks, do you know the release date of updated files ?  And will they be
downloaded automatically?

Thanks

**Comment by cristgl** [comment]
Hi @rhysxevans,

There is no ETA defined. They will be added in 3.10 which will be released in the following weeks. Yes, they will be downloaded automatically.

Kind regards,
Cristina

**Comment by Zenidd** [comment]
Hi again @rhysxevans,

We hope that Wazuh v3.10 will be ready as soon as possible. You can track our progress [here](https://github.com/wazuh/wazuh/projects/30).

I'm closing this ticket due to inactivity. Don't hesitate to open a new ticket or reopen this one if you need our help. 

On the other hand, if you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack. We will happy to help you in the Community channel.

Best regards, Juan Pablo Sáez
