### ISSUE TITLE
Shellshock alerts are no longer generated after emerging rules update

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-ruleset#544]
Hi all,

The  emerging-rules[https://rules.emergingthreats.net/open/suricata-4.1.5/emerging.rules.tar.gz] have been updated. This causes Shellshock alerts `31166` and `31167` to do not trigger:

https://github.com/wazuh/wazuh-ruleset/blob/6ab1822e35bf09d9d8a9fcc1605478630b6d8a7f/rules/0245-web_rules.xml#L235-L253

When reviewing differences I noticed some of the rules changed according to the md5sum:

![image](https://user-images.githubusercontent.com/46649922/72071855-01611900-32ed-11ea-867b-8aed1408f05c.png)

Also the Emerging Threads site shows the rules were updated yesterday:

https://rules.emergingthreats.net/open/suricata-4.1.5/

![image](https://user-images.githubusercontent.com/46649922/72071891-19389d00-32ed-11ea-924a-00b74767d121.png)

**Comment by iasdeoupxe** [comment]
Sure that these are "not longer generated" or do they just don't trigger e.g. an E-mail Alert anymore? I'm asking because it seems the level for 4xx and 5xx responses got lowered in https://github.com/wazuh/wazuh-ruleset/pull/541 based on a request in https://github.com/wazuh/wazuh-ruleset/pull/479#issuecomment-571361905

**Comment by jm404** [comment]
After reviewing and redeploying my environment I successfully generated the Shellshock alert with the id `31166`, it seems that something went wrong during the first provision which made impossible to generate the alert. After redeploying, I have been able to generate the alert multiple times without issues.

@iasdeoupxe , regarding https://github.com/wazuh/wazuh-ruleset/pull/541 and https://github.com/wazuh/wazuh-ruleset/pull/479#issuecomment-571361905 I've not tested it yet as I'm running on `3.11.1_7.5.1`. We'll deeply test those changes to ensure the alerts keep generating.

However, a review of the Wazuh rules associated with emerging rules might be a good idea in case some of it changed.

Best regards,

Jose

**Comment by iasdeoupxe** [comment]
I'm not sure if there is any relation between the emerging-rules / Suricata and the previously mentioned wazuh rules. It seems Wazuh is only providing handling of Suricata alerts but these rules haven't been touched since longer time:

https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0475-suricata_rules.xml

**Comment by Lopuiz** [comment]
Hello team,

Thanks for your feedback, @iasdeoupxe!

We can add new rules if users request them but, at the moment, there are other issues with high priority.

I'm sorry to close this issue, but it isn't in our roadmap.

Best regards,
Eva
