### ISSUE TITLE
Palo Alto Decoder src_ip instead of srcip

### ISSUE THREAD

**Issue by kyparisisg** [wazuh/wazuh-ruleset#683]
I have created a few custom rules under the local_rules.xml for palo alto logs to get more sophisticated alerts.
One of my rules consists of **<same_source_ip>** to check the frequency, but as I was troubleshooting to figure out why it was not working I saw that the source ip is given the field name of **src_ip** instead of **srcip** in the paloalto decoder.
When I changed the decoder's field name to **srcip**, I was able to get the alerts from my custom rules when the source ip was the same on my repeated logs. I address this as I have observed that **srcip** is the field name that is given throughout the rest decoders.
Is this something we can change on the palo alto decoder file? Or should I keep the changes only locally to myself? 
Thank you for your time and help in advance! 

Wazuh Version 3.13

**Comment by danimegar** [comment]
Hello @kyparisisg 
It seems Palo Alto decoder uses static or predefined fields and dynamic fields. The predefined fields are: user (dstuser), srcuser, srcip, dstip, srcport, dstport, protocol, action, id, url, data, extra_data, status and system_name.

I agree with you. Looking at the decoder, there are some fields that can be changed to predefined fields. In that way, the same_source_ip field will work. I will investigate further on this.

Also, from the next release Wazuh 3.13 on, it will be possible to use the field **<same_srcip>** instead of **<same_source_ip>** although both can be used.

**Comment by danimegar** [comment]
Hello again @kyparisisg 

On second thought, I think the decoder is fine. The point is the decoder does not use static fields but dynamic fields so I will you some ideas you can try:

1) I strongly recommend you to use the dynamic filter <same_field> instead of <same_source_ip>
`<same_field>src_ip</same_field>`
You will find more information in the [Wazuh documentation](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#same-field)

2) If you want to use the <same_source_ip> filter, you will have to overwrite the decoder and to change src_ip for srcip. [Here](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-decoder) you will find an example.

Regards,
Daniel.

**Comment by kyparisisg** [comment]
Hi Daniel,

Thank you very much for your clarification on this one. My thoughts were towards the first comment that you made about being persistent with the field names, but like you said the decoder is fine I will just swap to _<same_field>src_ip</same_field>_ .

Regards,
John
