### ISSUE TITLE
All rule id Windows

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh-ruleset#70]

**Comment by borbelyau** [comment]
[windows.txt](https://github.com/wazuh/wazuh-ruleset/files/1333216/windows.txt)

**Comment by borbelyau** [comment]
hey guys ... I hope it helps
was taken from the site https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/

**Comment by vikman90** [comment]
Hi, @borbelyau,

I'm sorry we don't understand the nature of this problem.

Could you clarify it, please?

Thank you.

**Comment by borbelyau** [comment]
The wazuh it captures several events with wrong descriptions ... the same id (windows id is unique) of windows event, is in more than one event ...

**Comment by vikman90** [comment]
Hi,

The idea is not necessarily to report every event as one rule.

Rules may group some events by matching regexes and/or classify them in order to select the most important ones that might impact your system.

For example, if you only are interested in receiving Windows events as alerts you may create one rule to match with all of them. Of course, the unique event ID from the Windows event will appear as a field named `eventID`) and you could group events by `eventID` in Kibana.

Best regards.

**Comment by borbelyau** [comment]
tks comrad

**Comment by vikman90** [comment]
You're welcome. Let me close this issue.
