### ISSUE TITLE
Alert in kibana dashboard

### ISSUE THREAD

**Issue by mansan951** [wazuh/wazuh-ruleset#704]
Is there possible to alert in kibana dashboard. If possible please give me solution and method.

**Comment by Lopuiz** [comment]
Hello,

Sorry, I don't understand your question. Could you give me more information?
If you want Wazuh generates alerts for some events (and shows them in the dashboard), you should create custom ruleset. You can follow our documentation to create rules and decoders: [Custom rules and decoders](https://documentation.wazuh.com/3.12/user-manual/ruleset/custom.html)

If you tell us the events in which you want to receive alerts, we try to help you.

Regards,
Eva

**Comment by mansan951** [comment]
I want ssh brute force attack alert in gmail. so i want to fired rule id 5712 in the configuration file. but i unable to alert in my gmail. my config is below
           <email_alerts>
		<email_to>gmail-address</email_to>
		<rule_id>5712</rule_id>
		<do_not_delay/>
	</email_alerts>
so how can i alert ssh brute force attack in my gmail. please give me configuration step in detail

**Comment by Lopuiz** [comment]
Wazuh doesn’t handle SMTP authentication. If your email service uses this, you will need to configure a server relay. I recommend reading the following post: [How to send an email notification with Wazuh](https://wazuh.com/blog/how-to-send-email-notifications-with-wazuh/)

Additionally, you can use the following configuration:
```
<email_alerts>
<rule_id>5712</rule_id>
</email_alerts>
```
Instead of the configuration used in the post:
```
  <alerts>
    <email_alert_level>9</email_alert_level>
  </alerts>
```

Once you configure it, if the issue persists, you can see Postfix logs to check if was Gmail server which denied the messages, or is Postfix or Wazuh configuration.

I hope it helps you.

Best regards,
Eva

**Comment by mansan951** [comment]
I have already configure smtp mail server and my rdp brute force alert work successfully and also alerting in my gmail. But ssh brute force attack not working.

**Comment by mansan951** [comment]
hello
issue has been solved.
