### ISSUE TITLE
Notes / hints to the OpenLDAP rules/decoders

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh-ruleset#75]
Not quite sure if this is the correct place to report this or if its better to post this in https://github.com/wazuh/wazuh-documentation (please let me know if i should re-open this there).

I'm running an OpenLDAP server on Debian 9/stretch and was wondering about the missing logging of OpenLDAP. It seems that the default of the loglevel (at least on Debian) is "none" these days. So you won't get the logs shown in:

https://github.com/wazuh/wazuh-ruleset/blob/v2.1.1/decoders/0185-openldap_decoders.xml#L10-L19

One has to first create a ldif file like the following:

```
dn: cn=config
replace: olcLogLevel
olcLogLevel: 256
```

and run it like:

```
ldapmodify -Y EXTERNAL -H ldapi:/// -f ./logging.ldif
```

to raise the loglevel (see https://www.openldap.org/doc/admin24/slapdconfig.html) to 256 which is the minimum to get those logs.

There seems to be another issue with the srcip as well as (at least on my setup) the IP within those logs is from the application doing the authentication, not from the user:

```
Oct  2 19:51:22 example slapd[30864]: conn=1068 fd=19 ACCEPT from IP=192.168.0.2:59800 (IP=0.0.0.0:636)
```

(192.168.0.2 is the IP of the web application doing the LDAP authentication).

**Comment by PSanchezR** [comment]
Hi Ghost,

If you want to get both IPs (destination and source) you have to change the decoder, instead of use:

```
<decoder name="openldap-connect">
    <parent>openldap</parent>
    <prematch>ACCEPT</prematch>
    <regex>^conn=(\d+) fd=\d+ ACCEPT from IP=(\S+):</regex>
    <order>id, srcip</order>
    <accumulate/>
</decoder>
```
You can use:

```
<decoder name="openldap-connect">
    <parent>openldap</parent>
    <prematch>ACCEPT</prematch>
    <regex>^conn=(\d+) fd=\d+ ACCEPT from IP=(\S+):\d+ \(IP=(\S+):</regex>
    <order>id, srcip, dstip</order>
    <accumulate/>
</decoder>
```
And if srcip and dstip are not in the right order you can change it by swaping those names in tag "order".

Using ossec-logtest with log entry:

`  Jan 11 09:26:57 hostname slapd[20872]: conn=999999 fd=64 ACCEPT from IP=10.10.248.27:33957 (IP=10.10.241.77:389)`

![ldap](https://user-images.githubusercontent.com/5520813/34434176-99460c00-ec84-11e7-8156-90b0618e5616.png)

We will include this change soon in wazuh-ruleset.

If you have any other question i'll be happy to help you.

Regards.

Pablo Sánchez.
