### ISSUE TITLE
How to trigger login from forbidden location in 0365-auditd_rules.xml and Network scan in 0280-attack_rules.xml

### ISSUE THREAD

**Issue by jingnanj** [wazuh/wazuh-ruleset#783]
Hi, staffs
Wazuh is a really great program! it has a lot of useful features that helped me protect my host server. But I faced two questions when I tested it with some attack programs. The first question is I don't know how to set ANOM_LOGIN_LOCATION for my server. The description of this rule looks very useful as IDS but I don't know how to trigger it. The second question is I was using nmap and nessus to scan all ports(0-65535) of my agent server. It'd didn't trigger any scan rule on Kibana.

here is the rule below, Could you please answer my question and give me an example log which can trigger those rules. 
Thanks!  
audit rule:
    <rule id="80724" level="5">
        <if_sid>80700</if_sid>
        <field name="audit.type">ANOM_LOGIN_LOCATION</field>
        <description>Auditd: login attempt from a forbidden location.</description>
        <group>audit_anom,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,gpg13_7.5,gdpr_IV_35.7.d,gdpr_IV_32.2,gdpr_IV_30.1.g,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
    </rule>

attack rule:
  <rule id="40601" level="10" frequency="12" timeframe="90" ignore="90">
    <if_matched_group>connection_attempt</if_matched_group>
    <description>Network scan from same source ip.</description>
    <same_source_ip />
    <info type="link">http://project.honeynet.org/papers/enemy2/</info>
    <mitre>
      <id>T1046</id>
    </mitre>
    <group>pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SI.4,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>

**Comment by JcabreraC** [comment]
Hello @jingnanj,

Have you configured your environment with auditd rules? First you must create the auditd rules and write them in the `var/log/auditd` directory so that Wazuh can read them and trigger the corresponding alerts. You can see how to make the auditd rules at the following link: 
http://manpages.ubuntu.com/manpages/groovy/man7/audit.rules.7.html

In addition, we have a blogspot that can serve as a guide to create rules for auditd:
https://wazuh.com/blog/monitoring-root-actions-on-linux-using-auditd-and-wazuh/

For your second question of port scanning, you should use some NIDS that can detect port scanning and send it to Wazuh through a `syslog` connection or by writing to a file that can read Wazuh
https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/remote.html

Depending on the NIDS, you may need to create custom rules:
https://documentation.wazuh.com/4.0/user-manual/ruleset/custom.html

Greetings,
Juan Cabrera

**Comment by jingnanj** [comment]
Thanks
