### ISSUE TITLE
MITRE: Enhancement of Command and Control mapping

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-ruleset#803]
This issue has been created to improve the mapping of several rules belonging to the **Command and Control** technique group from MITRE. 

Here are all the techniques with their respective rules that must be reviewed:

**Commands and Control:**

**T1043** Deprecated. (**Commonly Used Port**)

 Alternative: **T1571 Non-Standard Port**

- [x] Rule ID: **5706** :  `sshd: insecure connection attempt` It would require a child rule to confirm the technique, otherwise it may belong to **Credential Access** techniques instead. 

- [x] Rule ID: **11209**: `proftpd: Attempt to bypass firewall that can't adequately keep state of FTP traffic - Refused port` - It makes sense to use the new T1571 but it could also belong to **Credential Access**. 

- [x] Rule ID: **11512**:  `Multiple FTP errors from the same source` It would require a child rule to confirm the technique, otherwise it may belongs to **Credential Access** techniques. 

- [x] Rule ID: **82405**: `Potential malware` - Not related to the use of ports. Could belong to a different technique. 

**T1065 Uncommonly Used Port**
Changed to **T1571 Non-Standard Port** (Same as above)

- [x] Rule ID: **11209** : `proftpd: Attempt to bypass firewall that can't adequately keep state of FTP traffic. - Refused port` It is also included in the list above. It makes sense, but it could also be a Credential Access technique. 

**T1026** Deprecated (**Multiband Communication**)
No alternative given.

- No rules. But should still be removed from the framework.

**T1079  Multilayer Encryption**
Changed to **T1573 (Encrypted Channel)**

- No rules

**T1095 (Non-Application Layer Protocol)**

If ARP collisions are part of this technique. The following are correct (Otherwise, they are all wrong)

- [x] Rule ID: **4325** `PIX: ARP collision detected` It could be related to T0830 from Execution

- [x] Rule ID: **7209**  `Arpwatch: Possible arpspoofing attempt` It could be related to T0830 from Execution 

- [x] Rule ID: **24061** `ARP cache:` It could be related to T0830 from Execution 

- [x] Rule ID: **64011** `ASA: ARP collision detected`

If connections blocked by TCP Wrappers belong to this technique. The following are correct (Otherwise, they are wrong):

- [x] Rule ID: **2503** `syslog: Connection blocked by Tcp Wrappers`  looks like it may belong to **Credential Access**

- [x] Rule ID: **5601** `telnetd: Connection refused by TCP Wrappers`  looks like it may belong to **Credential Access**

- [x] Rule ID: **11107** `Connection blocked by Tcp Wrappers`  looks like it may belong to **Credential Access**

- [x] Rule ID: **11207** `proftpd: Connection refused by TCP Wrappers` looks like it may belong to **Credential Access**

Ipsec rules. They seem to fit the description:

- [x] Rule ID: **18658**,  **18659** , **18660**, **18661** -> `All related to Ipsec negotiation process` - They seem to fit description.  

- [x] Rule ID: **18662**: Same as above. But also has this technique added correctly: T1489 (Process stopped)

ICMP destination-unreachable:
 

- [x] Rule ID: **64223**  `Prohibit a packet from passing. Send an ICMP destination-unreachable back to the source host`

**T1132 Data Encoding**

- No rules. 

**T1219 Remote Access Software**

- No rules.

**T1008 Fallback Channels**

- No rules. 

**T1092 Communication Through Removable Media**

- No rules.

**T1104 Multi-Stage Channels**

- No rules.

**T1188 Multi-hop Proxy**
It is now **T1090**

There are rules mapped as T1090 even though the dashboards show T1188:

LGTM:

- [x] Rule ID: **35007** `Squid: Proxy Authentication Required: User is not authorized to use proxy`

- [x] Rule ID: **35052** `Squid: Multiple unauthorized attempts to use proxy.` Also mapping T1110  Brute Force from Credential Access

**Comment by odintree** [comment]
Hi team,

I am adding some more MITRE technique from `Commands and Control` that may require some changes here:

## T1032

#### Rules
- No rules

#### Status
Changed the number to T1573

---

## T1102

#### Rules
- 9510
- 30107
- 30307
- 31411

#### Status
- 9510 is fine
- 30107, 30307, 31411 is slightly related since the technique is a compromised system. But in this case I believe there should be much more rules that can be related to this MITRE. 

---

## T1172

#### Rules
- No rules

#### Status
- Now it is T1090.004 subtechnique of T1090 (we have it)

---

## T1483

#### Rules
- No rules

#### Status
- Now it is T1568.002 subtechnique of T1568 (we do not have it)

---

## T1024

#### Rules
- No rules

#### Status
- Now it is T1573
- Description has changed

---

## T1071

#### Rules
- 12101
- 81611
- 82405
- 24215

#### Status
- Fine. 24215, 82405, 12101 are regarding DNS. And 81611 is "Multiple default tunneling setting"
- But rule 81610 has no MITRE T1071. It is a parent of 81611 that will got triggered if 81610 has a frequency of 18 times

---

## T1071

#### Rules
- 12101
- 81611
- 82405
- 24215

#### Status
- Fine. 24215, 82405, 12101 are regarding DNS. And 81611 is "Multiple default tunneling setting"
- Rule 81610 has no MITRE T1071. It is a parent of 81611 that will got triggered if 81610 has a frequency of 18. 

---

## T1094

#### Rules
- No rules

#### Status
- It is now combined with T1095 (we have it)

---

## T1105

#### Rules
- No rules

#### Status
- It is now changed to T1544 (we do not have it)
- Checking the description that we have it seems like partly it was also related to a new T1105 (different name though)

---

## T1205

#### Rules
- No rules

#### Status
- It is now changed to T1205.001 that is a subtechnique of T1205 (that now is Traffic Signaling)
- Description was changed also. 

Kind regards,
Bin.

**Comment by 72nomada** [comment]
@JavierBejMen @Nekaze check this pls. 
add this c&c info to your work in [#7566](https://github.com/wazuh/wazuh/issues/7556).
report and close here when done, please.

**Comment by Nekaze** [comment]
Hello, @JavierBejMen and I have worked on some of the rules mentioned here, in order to acomodate them to the new MITRE info that is going to be added. 

We are going in order from oldest to most recent.

These are the rules we have looked and updated so far:

Non-Standard Port:
- 5706
- 11209
- 11512
- 82405
- 4325
- 7209
- 24061
- 64011

TCP Wrappers -  Rules too generic
- 2503
- 5601
- 11107
- 11207

Ipsec
- 18658
- 18569 too generic
- 18660 too generic
- 18661 too generic

- ICMP too generic
- 64223

- LGTM too generic
- 35007
- 35052 

We've found some rules to be OK, some of them needed correction in the Technique ID, and some of them are too generic to be put into a MITRE Technique, so will probably need more specific children rules, or rework. 

We will continue to update as we move forward with the rest of the techniques mentioned here for C2

Regards
Nicolas

**Comment by Nekaze** [comment]
Evaluation of all the rules presented here has concluded. The last updates are this:

-  9510 - OK, Added subtech T1102.002
-  30107 - OK
-  30307 - OK
-  31411 - MARKED FOR REVIEW, I dont believe T1102 is right for this rule 

-  12101 - OK, added subtech T1071.004; removed T1149 as its deprecated
-  81611 - Updated to T1572: Protocol Tunneling
-  82405 - OK, added subtech T1071.004
-  24215 - OK, added subtech T1071.004

As part of the work we are doing in https://github.com/wazuh/wazuh/issues/7556, we will eventually add proper MITRE mapping for the rest of the C2 techniques mentioned in this issue.

Kind regards
Nicolas

**Comment by Nekaze** [comment]
Closing this as the evaluation of the here mentioned rules has concluded.

Further analysis of C2 techniques and improving of the current ruleset is being tracked in https://github.com/wazuh/wazuh/issues/7556

Kind regards
Nicolas
