### ISSUE TITLE
Oracle monitoring - Best alternative.

### ISSUE THREAD

**Issue by lucio2047** [wazuh/wazuh-ruleset#821]
Hello, how are you?

I have a doubt: what is it the best option to monitor Oracle database? 

I was thinking about mounting a syslog server on Wazuh and then try to configure Oracle to send syslogs security logs to Wazuh server, but my doubt is how to customize these logs, may be through specific decoder?

Thank you very much!!

**Comment by juliancnn** [comment]
Hi @lucio2047, I'm fine and you?

You have 2 options to solve this.
1) As you said, you could use Wazuh syslog server.
2) Another option is to store the logs in a file and collect them with [logcollector](https://documentation.wazuh.com/4.0/user-manual/capabilities/log-data-collection/index.html). For this you should have the Wazuh Agent installed on the Oracle Database host.

If you already have the wazuh agent installed, the second option will allow you to save the logs in the agent and also be able to process them in the manager.
Currently, Wazuh supports more than 3k rules that accomplish technologies such as syslog, docker, nginx, etc.
At this time the default ruleset does not include the rules and decoders for dealing with Oracle Database, but I will gladly help you create custom rules and decoders for this type of log.

I have looked in the oracle database 21c documentation for samples of logs. Unfortunately, I have not found them.
If you wish, you could share logs with me, in this way we can together create the rules and decoders you need.

Regards, 
Julian

**Comment by lucio2047** [comment]
Hi Julian,

Thank you very much for your email.

Just perfect about your explanation.

Several explanation:

1) Right now, I need to monitor user logon to Oracle database because the
main business application uses accounts defined directly in the database
engine . For example, suppose my user in the application "A" is "prueba".
Well, "prueba" is a user defined directly in the Oracle Database Engine, it
is not a user defined inside the application, for example in a table, is a
user defined directly to Oracle Engine. For that reason, I would like to
monitor when a critarl application user, for example "admin" try to login
to application "A".

2) As I could read from your response, it is not possible to monitor Oracle
activities executed over the database. I mean activities about
database administration. Supposedly I´d like to monitor a typical user's
administration, it is nos possible, is it?

Thank you very much Julian!

pd. gracias por toda tu ayuda!

**Comment by juliancnn** [comment]
@lucio2047,

Now I understand what you want, thank you very much for the explanation.
Wazuh has multiple capabilities, one of them is log monitoring. These can be collected by the agent or received directly in the Manager via syslog.
In order for Wazuh Manager to process the information you want (regardless of how logs are collected), Oracle Database must generate and save logs with this.
I have looked for this information in the following documents:
[Oracle® DatabaseDatabase Administrator’s Guide](https://docs.oracle.com/en/database/oracle/oracle-database/19/admin/database-administrators-guide.pdf)
[Oracle® DatabaseDatabase Administrator's Reference](https://docs.oracle.com/en/database/oracle/oracle-database/19/unxar/administrators-reference-linux-and-unix-system-based-operating-systems.pdf)
Unfortunately I have not found how to store logs with this information in files.
If you can do this, could you share the logs with us? This way I will help you create the custom rules and decoders you need

Regards,
Julian

**Comment by lucio2047** [comment]
Hi Julian,

I have another question:

First off all, I´m gonna configure Oracle to send an audit trail through
syslog. Once this is done, the second task is configuring Wazuh to accept
connection from Oracle through syslog (this is done, I made it yesterday)
with the following configuration:

  <remote>
    <connection>syslog</connection>
    <port>514</port>
    <protocol>udp</protocol>
    <allowed-ips>a.a.a.a</allowed-ips>    ---where a.a.a.a  is the Oracle´s
IP.
    <local_ip>b.b.b.b</local_ip>                ---where b.b.b.b  is my
local Wazuh Manager
  </remote>

Finally, I can understand there is on rules to support o decode Oracle
Syslog server, but how can I do in order to see the original syslog from
Oracle in order to understand its composition and try to make an specific
decoder for Oracle Syslog Audit Trail?, Does it exist a possibility?
Because to generate a specific decoder is necessary to understand the
original logs in order to parse through decoder, isn`t it?

Thank you in advance!!

**Comment by juliancnn** [comment]
@lucio2047, that's an excellent question.

The syslog configuration seems fine, and there is a configuration with which you could check that you receive the logs (events) and see what logs you receive.
For that, enable the [logall](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/global.html#logall) option in `/var/ossec/etc/ossec.conf` (Manager):
```xml
<ossec_config>
  <global>
    ...
    <logall>yes</logall>
    ...
  </global>
  ...
</ossec_config>
 ```
Then, restart Wazuh manager and you will see the events to come in /var/ossec/logs/archives/archives.log
In that way, if you see the  Oracle Syslog log in the archives.log, the Manager is recollecting them correctly.
You could also see the logs that arrive to create the necessary rules and decoders.

My recommendation is not to keep this option active in production, since by storing all the events that reach the manager it would use disk space unnecessarily.

Please let me know if this is helpful.

**Comment by lucio2047** [comment]
Julian , thank you very much.

It's perfect, but I have only one question: when you indicate the following
" *My recommendation is not to keep this option active in production, since
by storing all the events that reach the manager it would use disk space
unnecessarily" *I don`t understand that, I mean this configuration
(<logall>yes</logall>)is only to corroborate syslog event is arriving from
Oracle?, and then?, suppose the log arrives correctly, what is the next
step? Create specific decoders?, but If I create a specific decoder but I
don`t turn on the <logall>yes</logall> configuration, how do logs go to
Wazuh?

Thank you very much.

**Comment by juliancnn** [comment]
You're welcome @lucio2047

The Wazuh environment is designed to run 24/7/365.
For example, in a small implementation (50/60 agents) you could process thousands or maybe millions of events per month. By leaving the `logall` option activated, you would be saving those events in a file unnecessarily. I don't know if this is the case, that is why my recommendation is to activate it for as long as you need it to see the logs, analyze the formats and test decoders.

Once you have the logs, it is possible to test rules and decoders with the ossec-logtest tool.
This tool is intended to test the wazuh ruleset (including its custom rules and decoders) through user-supplied logs

We have a blog post that you might find interesting:
- [Creating decoders and rules from scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/)	

We also have more information in our documentation:
-  [Custom rules and decoders](https://documentation.wazuh.com/4.0/user-manual/ruleset/custom.html)

I hope this answers your questions
Please do not hesitate to ask, I will be happy to help you every time you need it!

**Comment by lucio2047** [comment]
Hello Julian,

Thank you very much for your email. I have several great questions.

First of all, It is better to begin from this page
https://documentation.wazuh.com/4.0/user-manual/capabilities/log-data-collection/how-it-works.html
.

Accordingly with the image about infrastructure of Wazuh, log are collected
through two mains forms:

    1) Using agent: which takes logs from Windows Event Log or Monitored
Files.
    2) Using Rsyslog: for example sending logs through syslog.

Several questions for 1) :

            1.1) How does Wazuh server indicate to remote agents how to
collect logs via Monitored Files or Windows Event Log. Which configuration
does Wazuh Server use in order to do that?, At ossec.conf?, In the agent
side when deploy and registering a client based on the remote operating
system?

            1.2) Where does Wazuh Server save logs from Agent? (I read it
is possible to send to the output database, but forget this possibility for
this moment). Does Wazuh server save all logs from agents or only those
that match with rules defined and the rest logs are eliminated and not
saved?

  Several questions for 2) :

            2.1) If I configure the syslog to receive logs from Oracle  and
Oracle to send syslog to Wazuh server (like I was discussing in our last
emails), what does it happend?, all logs from Oracle through syslog are
saved at specific location file in Wazuh Server or only those which match
with specific ruleset?

Thank you very much!

**Comment by juliancnn** [comment]
hi @lucio2047 


> 1.1) How does Wazuh server indicate to remote agents how to
collect logs via Monitored Files or Windows Event Log. Which configuration
does Wazuh Server use in order to do that?, At ossec.conf?, In the agent
side when deploy and registering a client based on the remote operating
system?

To collect logs the [localfile](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/localfile.html#reference-ossec-localfile) option is used in the [ossec.conf](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/index.html#reference-ossec-conf). This capacity is available to both the agent and the manager.
If you want to collect logs from manager files you must configure it in the manager, and if you want to collect logs from agent files you must configure it in the agent.

If you want to know what configurations are available for the agent and the manager, you could find them [here](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/index.html).


>  1.2) Where does Wazuh Server save logs from Agent? (I read it
is possible to send to the output database, but forget this possibility for
this moment). Does Wazuh server save all logs from agents or only those
that match with rules defined and the rest logs are eliminated and not
saved?

This depends on the manager config. In the default configuration, the logs that generate alerts are stored as part of the alert in the file `/var/ossec/logs/alerts/alerts.log` and the rest are discarded. 
This configuration could be changed with the [log_all](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/global.html#logall) option that I mentioned earlier, causing all the agent logs to be stored  in `/var/ossec/logs/archives/archives.log`

>  2.1) If I configure the syslog to receive logs from Oracle  and
Oracle to send syslog to Wazuh server (like I was discussing in our last
emails), what does it happend?, all logs from Oracle through syslog are
saved at specific location file in Wazuh Server or only those which match
with specific ruleset?

Answer 1.2 is still valid for this case.

Please let me know if this information is useful to you .

Regards,

**Comment by lucio2047** [comment]
Hi Julian,

When you say *"......logs that generate alerts are stored as part of the
alert in the file /var/ossec/logs/alerts/alerts.log and the rest are
discarded...."* I have the following doubt:

A) In my case, Wazuh does not have logall options setting in "yes", for
that reason *"...only logs that generate alerts are store as part of the
alert..."* as you mentioned earlier, ok?, Following your previous
explanation, I have an agent on a Windows System reporting logs to Wazuh
Server, but not only generate alerts, for example logon activities (Rule ID
60137) , so I suppose logon activities are not saving at
/var/ossec/logs/alerts/alerts.log because this kind of event is not
generating alerts by mail and I only can see them through Wazuh console.

Do you understand my question?

Thank you very much.

**Comment by juliancnn** [comment]
Hi @lucio2047 

I understand your question.  I will try to answer your question as well as possible, if it is not good enough, please let me know and I will try to explain it in another way.

The manager's configuration file (`/var/ossec/etc/ossec.conf`)  has a section called [alert](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/alerts.html), by default it presents the following configuration:

```
  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
```
**log_alert_level** : indicates the minimum level that a matching rule must have to generate an alert

For example, the rule with [ID 60137 is level 3](https://github.com/wazuh/wazuh/blob/170cc4abbb0fc05b2ed8697990e89d64c9168e18/ruleset/rules/0580-win-security_rules.xml#L371), that is why it generates an alert that can be seen in alert file (`/var/ossec/logs/alerts/alerts.log`) and also in Kibana (`Wazuh->Modules->Security events`).

**email_alert_level** indicates the minimum level for an alert to generate an email notification. This tells us that a level 3 rule will generate an alert but as it is not greater than 12 it will not send an email.


Please let me know if this is helpful..
Regards,
Julian

**Comment by lucio2047** [comment]
Thank you for the clarification.

Las Fryday following your explanation I executed cat
/var/ossec/logs/alerts/alerts.log
and I could see the event like 60137 and I could wonder alert is not only
those generate alert by mail as you explain recently. For that reason thank
you very much, you are very clear.

Thank you very much!

**Comment by juliancnn** [comment]
You're welcome! I'm glad to know that. We are here to help.
Feel free to ask.

Regards
Julian
