### ISSUE TITLE
New rules require JSON Decoder in 3.0.0 but not yet released

### ISSUE THREAD

**Issue by grant-traynor** [wazuh/wazuh-ruleset#88]
It looks as though there's an incompatibility between the released rulesets and application. The new rules now rely on a JSON_Decoder, but wazuh-master is still at 2.1.1 which doesn't have it? Assume it's fixed in 3.0.0?

On Ubuntu 14.04, whazuh-master after update_ruleset.py:

2017/12/06 14:48:35 ossec-testrule: INFO: Reading decoder file ruleset/decoders/0006-json_decoders.xml.
2017/12/06 14:48:35 ossec-testrule: ERROR: (2110): Invalid decoder argument for plugin_decoder: 'JSON_Decoder'.
2017/12/06 14:48:35 ossec-testrule: CRITICAL: (1202): Configuration error at 'ruleset/decoders/0006-json_decoders.xml'. Exiting.

**Comment by vikman90** [comment]
Hi @grant-traynor,

we have just detected this issue and are working on fixing it. In fact we have reverted the branch _stable_ to v2.1.1 until we get this problem fixed.

In the meantime, this command should fix your issue if you're using Wazuh v2.1.1:

```
# /var/ossec/bin/update_ruleset.py -b
```

It will restore your backup. In the case that command doesn't work, try:

```
# rm /var/ossec/ruleset/{rules/*,decoders/*}; /var/ossec/bin/update_ruleset.py; /var/ossec/bin/update_ruleset.py
```

The first upgrade (that upgrades the upgrade script itself) may fail but the latter should work.

We do apologize for the inconveniences.
Kind regards.

**Comment by grant-traynor** [comment]
Thanks so much for the information.

At the moment I'm pulling both branches with git under ansible.

I need the Ubuntu 14.04 OpenSCAP file in the 3.0.0 branch, but the 2.1.1 ossec files.

No rush, really appreciate your work. Outstanding!

**Comment by kravietz** [comment]
When trying to recover from the decoder error using the double upgrade command but I'm getting the following error:

```
You already have the latest version of rules.

The following rootchecks will be updated:
	cis_debian_linux_rcl.txt
ERROR: Unknown: [Errno 2] No such file or directory: '/var/ossec/etc/rootcheck/cis_debian_linux_rcl.txt'.
Exiting.
```

**Comment by Q1tum** [comment]
Running into the same problem as described as @kravietz:

```
update_ruleset.py -r 
### Wazuh ruleset ###
You already have the latest version of rules.

The following rootchecks will be updated:
	cis_debian_linux_rcl.txt
ERROR: Unknown: [Errno 2] No such file or directory: '/var/ossec/etc/rootcheck/cis_debian_linux_rcl.txt'.
Exiting.
```

**Comment by cyberfarer** [comment]
I'm having this issue, too. The instructions above have not helped. If I remove the json rules then it complains about 0350-amazon_rules.xml and then 0475-suricata_rules.xml. Is it whack-a-mole?

**Comment by daibakes** [comment]
Experiencing the same. Instructions have not helped and currently Wazuh is in a failed state. 
OS is Ubuntu 16.04 LTS, Wazuh on v2.1.1

Any suggestions on how to get this up and running?

**Comment by mgmacias95** [comment]
Hello all,

Last week, the stable version of the Wazuh Ruleset was set to the v3.0. Since the `update_ruleset.py` uses these branch to update it, all 2.1 installations will be broken.

What is the reason for the following error?

```
ERROR: Unknown: [Errno 2] No such file or directory: '/var/ossec/etc/rootcheck/cis_debian_linux_rcl.txt'.
``` 

In Wazuh 2.1, _rootcheck_ files are stored in `/var/ossec/etc/shared`. In Wazuh 3.0, the path changed to `/var/ossec/etc/rootcheck`. When updating the ruleset, the `update_ruleset.py` script is also updated. When it's executed again to restore the backup, that error appears.

To solve this, the ruleset must be restored manually:

```
# wget https://github.com/wazuh/wazuh-ruleset/archive/2.1.zip
# unzip 2.1.zip
# rm -r /var/ossec/ruleset/rules && cp -r wazuh-ruleset-2.1/rules /var/ossec/ruleset/rules
# rm -r /var/ossec/ruleset/decoders && cp -r wazuh-ruleset-2.1/decoders /var/ossec/ruleset/decoders
# rm -r /var/ossec/etc/shared && cp -r wazuh-ruleset-2.1/rootchecks /var/ossec/etc/shared
# cp wazuh-ruleset-2.1/VERSION /var/ossec/ruleset/VERSION
```

Best regards,
Marta

**Comment by sempervictus** [comment]
For shared ELK setups where other data is being ingested, upgrades to Wazuh 3 are not possible. ES6 breaks a lot of other things running through the ELK stack, and in many cases revised versions for monitoring those telemetry sources wont be available for ES6 for months to come.
This is a security stack, so not having rules == not working.
Can Wazuh version the rules repos to the Wazuh revisions and not make silent breaking changes off the cuff (aka, the rule updater still running even though its pulling content for the wrong version, and not creating log entries about this even in the syslog of the machine, much less the log factory that is ELK)? Also, do you guys have the last version of that 2.1 rules repo somewhere so that people who had to restore from the packages can get "somewhat current?" 
The operations/procedures around this version rollover are far less polished than the product itself, and that can be enough to illicit some decision maker outside the technical implementation sphere to deem it "unstable open source garbage" and force us to remove it without allocating budget for a proper commercial replacement. We saw all of this with the OSSIM mess years ago - initially it was too unstable to use in production because updates broke all the things (and the folks responsible for maintaining it got all the heat inside places using it), then it became a bloated mess of costs and broken functionality. Not sure how they're doing today, they still exist as a company, but they definitely didn't end up making the impact in the space they were aiming to because they lost momentum in adoption due to infrastructure issues with production context, not even the product itself (at the onset anyway).

**Comment by jesuslinares** [comment]
Hi @sempervictus ,

> Can Wazuh version the rules repos to the Wazuh revisions and not make silent breaking changes off the cuff (aka, the rule updater still running even though its pulling content for the wrong version, and not creating log entries about this even in the syslog of the machine, much less the log factory that is ELK)?

The repository is already versioned:
- Latest version: https://github.com/wazuh/wazuh-ruleset/tree/stable
- 2.0.x version: https://github.com/wazuh/wazuh-ruleset/tree/2.0
- 2.1.x version: https://github.com/wazuh/wazuh-ruleset/tree/2.1
- 3.0.x version: https://github.com/wazuh/wazuh-ruleset/tree/3.0
- 3.1.x version: https://github.com/wazuh/wazuh-ruleset/tree/3.1

We are improving the script to download the latest compatible version. The script will not upgrade the ruleset if the manager version and the new ruleset version are not compatible.

> Also, do you guys have the last version of that 2.1 rules repo somewhere so that people who had to restore from the packages can get "somewhat current?"

This is the procedure:
```
# wget https://github.com/wazuh/wazuh-ruleset/archive/2.1.zip
# unzip 2.1.zip
# rm -r /var/ossec/ruleset/rules && cp -r wazuh-ruleset-2.1/rules /var/ossec/ruleset/rules
# rm -r /var/ossec/ruleset/decoders && cp -r wazuh-ruleset-2.1/decoders /var/ossec/ruleset/decoders
# rm -r /var/ossec/etc/shared && cp -r wazuh-ruleset-2.1/rootchecks /var/ossec/etc/shared
# cp wazuh-ruleset-2.1/VERSION /var/ossec/ruleset/VERSION
```

Thanks for your feedback.
